# kindly generated by appropriated Rails generator
Mailjet.configure do |config|

  config.api_key = ENV['config.api_key']
  config.secret_key = ENV['config.secret_key']
  config.default_from = ENV['config.default_from']

end
