# kindly generated by appropriated Rails generator
Mailjet.configure do |config|

  config.api_key = ENV['KEY API']
  config.secret_key = ENV['KEY API']
  config.default_from = ENV['DEFAUT MAIL']

end
