# kindly generated by appropriated Rails generator
Mailjet.configure do |config|

  config.api_key = ENV['e5733db8304ffea17f2f47d1d64d7a6f']
  config.secret_key = ENV['5ecae41aed35e6890760eb9d0a994ae2']
  config.default_from = ENV['agenceaixit@gmail.com']

end
